"""
Plan-level expense events (plan.expenses.events[]).

Every type, field and default here was captured on 2026-09-13 by adding one expense of each
kind through the ProjectionLab 4.6 "New Expense" dialog (name + amount only, everything else
left at its default) and reading the record back with exportData(). The raw captures live in
docs/fixtures/expenses/. Models allow extra fields so nothing the app writes is dropped on a
round trip.

UI label -> stored `type` (and `subtype`):
  Living Expenses   living-expenses
  Rent              rent
  Debt              debt
  Student Loans     debt  (subtype "student-loans")
  Dependent         dependent-support
  Education         education
  Health Care       health-care
  Vacation          vacation
  Wedding           wedding
  Charity           charity
  Travel            travel
  Medical Expenses  medical
  Emergency         emergency
  Custom Expense    other
  (Medicare)        medicare  — generated by the app, never added by hand
"""
from __future__ import annotations

import uuid
from typing import Annotated, Any, Literal, Optional
from pydantic import BaseModel, Field

from .common import TimeRef


def _kw(value: str, modifier: str | None = None) -> TimeRef:
    return TimeRef(type="keyword", value=value, modifier=modifier)


class ExpenseYearlyChange(BaseModel):
    """How the expense amount changes year-over-year ("Change Over Time" in the UI).

    Observed `type` values and the UI label that produces them:
      "match-inflation"  Match Inflation            (default for most types)
      "none"             no change                  (default for once-off types and debt)
      "inflation+"       Inflation + N% per year    (default for health-care / medical, amount=2)
    Income and asset events additionally use "increase", "decrease", "match-inflation-plus",
    "appreciate", "depreciate".
    """
    model_config = {"extra": "allow"}

    type: str = "match-inflation"
    amount: float = 0
    amountType: str = "today$"
    limit: Optional[float] = 0
    limitEnabled: Optional[bool] = False
    limitType: Optional[str] = "today$"


YC_INFLATION = lambda: ExpenseYearlyChange()                                   # noqa: E731
YC_NONE = lambda: ExpenseYearlyChange(type="none")                             # noqa: E731
YC_INFLATION_PLUS_2 = lambda: ExpenseYearlyChange(type="inflation+", amount=2)  # noqa: E731


class BaseExpense(BaseModel):
    """Fields present on every expense event the UI creates."""
    model_config = {"extra": "allow"}

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: str
    name: str
    title: str
    icon: str
    color: str
    owner: Literal["me", "spouse"] = "me"
    planPath: Literal["expenses"] = "expenses"
    amount: float = 0
    amountType: str = "today$"          # observed: "today$", "grow$" (health-care, medical)
    frequency: str = "yearly"           # observed: "yearly", "monthly", "once"
    frequencyChoices: bool = True
    start: TimeRef = Field(default_factory=lambda: _kw("beforeCurrentYear"))
    end: TimeRef = Field(default_factory=lambda: _kw("endOfPlan", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_INFLATION)
    key: Optional[float] = None         # random ordering key written by the app; preserve, never invent


class SpendingExpense(BaseExpense):
    """Every non-debt expense also carries a Flexibility setting."""
    spendingType: str = "essential"     # observed: "essential", "discretionary"


# ── Recurring living costs ────────────────────────────────────────────────────

class LivingExpense(SpendingExpense):
    type: Literal["living-expenses"] = "living-expenses"
    title: str = "Living Expenses"
    icon: str = "mdi-home-city"
    color: str = "blue-lighten-1"


class RentExpense(SpendingExpense):
    type: Literal["rent"] = "rent"
    title: str = "Rent"
    icon: str = "mdi-home-currency-usd"
    color: str = "teal-lighten-1"
    frequency: str = "monthly"


class DependentSupportExpense(SpendingExpense):
    """UI: "Dependent". The Name field is labelled "Dependent Name"; ends at retirement by default."""
    type: Literal["dependent-support"] = "dependent-support"
    title: str = "Dependent"
    icon: str = "mdi-human-child"
    color: str = "purple-lighten-1"
    end: TimeRef = Field(default_factory=lambda: TimeRef(type="milestone", value="retirement", modifier="include"))


class EducationExpense(SpendingExpense):
    type: Literal["education"] = "education"
    title: str = "Education"
    icon: str = "mdi-school"
    color: str = "light-green-lighten-1"
    itemized: bool = False
    taxDeductible: bool = False


class HealthCareExpense(SpendingExpense):
    """Amounts are "grow$" and default to inflation + 2%/yr (healthcare inflation)."""
    type: Literal["health-care"] = "health-care"
    title: str = "Health Care"
    icon: str = "mdi-heart-plus"
    color: str = "pink-lighten-1"
    amountType: str = "grow$"
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_INFLATION_PLUS_2)
    healthcareType: str = "standard"
    deductFromIncomeId: str = ""


class MedicalExpense(SpendingExpense):
    """UI: "Medical Expenses". Like health-care but starts now and can repeat."""
    type: Literal["medical"] = "medical"
    title: str = "Medical Expenses"
    icon: str = "mdi-medical-bag"
    color: str = "red-lighten-1"
    amountType: str = "grow$"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_INFLATION_PLUS_2)
    deductFromIncomeId: str = ""
    repeat: bool = False


# ── Discretionary / one-off events ───────────────────────────────────────────

class VacationExpense(SpendingExpense):
    type: Literal["vacation"] = "vacation"
    title: str = "Vacation"
    icon: str = "mdi-beach"
    color: str = "cyan-lighten-1"
    spendingType: str = "discretionary"
    repeat: bool = False


class TravelExpense(SpendingExpense):
    type: Literal["travel"] = "travel"
    title: str = "Travel"
    icon: str = "mdi-airplane"
    color: str = "cyan-lighten-1"
    spendingType: str = "discretionary"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    repeat: bool = False


class WeddingExpense(SpendingExpense):
    """One-off; `switchToMarried` = "Update Status to Married" checkbox."""
    type: Literal["wedding"] = "wedding"
    title: str = "Wedding"
    icon: str = "mdi-diamond-stone"
    color: str = "pink-lighten-1"
    spendingType: str = "discretionary"
    frequency: str = "once"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_NONE)
    switchToMarried: bool = False
    repeat: bool = False


class CharityExpense(SpendingExpense):
    """One-off; itemized and deductible at federal + state level by default."""
    type: Literal["charity"] = "charity"
    title: str = "Charity"
    icon: str = "mdi-charity"
    color: str = "blue-lighten-1"
    spendingType: str = "discretionary"
    frequency: str = "once"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_NONE)
    donationType: str = "standard"
    itemized: bool = True
    taxDeductible: bool | list[str] = Field(default_factory=lambda: ["federal", "state"])
    repeat: bool = False


class EmergencyExpense(SpendingExpense):
    type: Literal["emergency"] = "emergency"
    title: str = "Emergency"
    icon: str = "mdi-weather-lightning"
    color: str = "red-lighten-1"
    frequency: str = "once"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_NONE)
    repeat: bool = False


class CustomExpense(SpendingExpense):
    """UI: "Custom Expense" (stored type "other")."""
    type: Literal["other"] = "other"
    title: str = "Custom Expense"
    icon: str = "mdi-currency-usd-circle"
    color: str = "brown-lighten-1"
    itemized: bool = False
    taxDeductible: bool | list[str] = False
    deductFromIncomeId: str = ""
    repeat: bool = False


# ── Debt-shaped expenses ─────────────────────────────────────────────────────

class DebtExpense(BaseExpense):
    """UI: "Debt" / "Student Loans". A loan payoff modelled as an expense: `amount` is the
    balance, `monthlyPayment` the payment, with interest/compounding/forgiveness settings.
    No `spendingType`."""
    type: Literal["debt"] = "debt"
    title: str = "Debt"
    icon: str = "mdi-weight-pound"
    color: str = "orange-lighten-1"
    subtype: Optional[str] = None       # "student-loans" for the Student Loans choice
    frequency: str = "monthly"
    start: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    end: TimeRef = Field(default_factory=lambda: _kw("never"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_NONE)
    effectiveDate: TimeRef = Field(default_factory=lambda: _kw("now", "include"))
    interestRate: float = 0
    interestType: str = "compound"
    compounding: str = "daily"
    monthlyPayment: float = 0
    monthlyPaymentType: str = "today$"
    hasForgiveness: bool = False
    forgiveAt: TimeRef = Field(default_factory=lambda: _kw("now", "include"))


def student_loans_defaults() -> dict[str, Any]:
    return {"subtype": "student-loans", "title": "Student Loans", "icon": "mdi-school", "color": "lime-lighten-1"}


# ── Generated ────────────────────────────────────────────────────────────────

class MedicareExpense(SpendingExpense):
    """Generated by the app from the About You ages; `_meta.deletion == "locked"`."""
    type: Literal["medicare"] = "medicare"
    title: str = "Medicare"
    icon: str = "mdi-hospital-box"
    color: str = ""
    generated: bool = True
    frequencyChoices: bool = False
    partAPremium: float = 0
    partBPremium: float = 0
    partDPremium: float = 0
    supplementalPremium: float = 0
    supplementalType: str = "none"
    healthcareInflationModifier: float = 2
    meta: Optional[dict[str, Any]] = Field(default=None, alias="_meta")


Expense = Annotated[
    LivingExpense | RentExpense | DependentSupportExpense | EducationExpense | HealthCareExpense
    | MedicalExpense | VacationExpense | TravelExpense | WeddingExpense | CharityExpense
    | EmergencyExpense | CustomExpense | DebtExpense | MedicareExpense,
    Field(discriminator="type"),
]

EXPENSE_MODELS: dict[str, type[BaseExpense]] = {
    "living-expenses": LivingExpense,
    "rent": RentExpense,
    "dependent-support": DependentSupportExpense,
    "education": EducationExpense,
    "health-care": HealthCareExpense,
    "medical": MedicalExpense,
    "vacation": VacationExpense,
    "travel": TravelExpense,
    "wedding": WeddingExpense,
    "charity": CharityExpense,
    "emergency": EmergencyExpense,
    "other": CustomExpense,
    "debt": DebtExpense,
    "medicare": MedicareExpense,
}


class NewCustomExpense(BaseModel):
    """Parameters for adding a Custom Expense (stored type "other") to a plan."""
    name: Annotated[str, Field(description="Display name, e.g. 'Wedding'.")]
    amount: Annotated[float, Field(description="Amount in today's dollars.")]
    frequency: Annotated[str, Field(description='"monthly", "yearly" or "once".')] = "monthly"
    owner: Literal["me", "spouse"] = "me"
    spendingType: Annotated[str, Field(description='"essential" or "discretionary".')] = "essential"
    start: TimeRef = Field(default_factory=lambda: _kw("beforeCurrentYear"))
    end: TimeRef = Field(default_factory=lambda: _kw("endOfPlan", "include"))
    yearlyChange: ExpenseYearlyChange = Field(default_factory=YC_INFLATION)
    taxDeductible: bool = False
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    def to_expense(self) -> CustomExpense:
        return CustomExpense(**self.model_dump())


ExpenseType = Literal[
    "living-expenses", "rent", "dependent-support", "education", "health-care", "medical",
    "vacation", "travel", "wedding", "charity", "emergency", "other", "debt", "student-loans",
]


class NewExpense(BaseModel):
    """Parameters for adding an expense of any verified type to a plan.

    Only `type`, `name` and `amount` are required; every other field defaults to exactly what
    the ProjectionLab "New Expense" dialog would store for that type. `student-loans` is the
    Debt type with the Student Loans subtype/icon.
    """
    type: Annotated[ExpenseType, Field(description="Expense kind (UI choice). See docs/schema.md for what each one stores.")]
    name: Annotated[str, Field(description="Display name.")]
    amount: Annotated[float, Field(description="Amount per `frequency` in today's dollars (for debt: the balance).")]
    owner: Literal["me", "spouse"] = "me"
    frequency: Annotated[Optional[str], Field(description='"monthly", "yearly" or "once". Default depends on type.')] = None
    spendingType: Annotated[Optional[str], Field(description='"essential" or "discretionary". Ignored for debt.')] = None
    start: Optional[TimeRef] = None
    end: Optional[TimeRef] = None
    yearlyChange: Optional[ExpenseYearlyChange] = None
    extra: Annotated[dict[str, Any], Field(description="Any other type-specific fields (e.g. monthlyPayment, interestRate, switchToMarried, taxDeductible).")] = Field(default_factory=dict)
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    def to_expense(self) -> BaseExpense:
        kind = self.type
        kwargs: dict[str, Any] = {"id": self.id, "name": self.name, "amount": self.amount, "owner": self.owner}
        if kind == "student-loans":
            kind = "debt"
            kwargs.update(student_loans_defaults())
        model = EXPENSE_MODELS[kind]
        for f in ("frequency", "start", "end", "yearlyChange"):
            if getattr(self, f) is not None:
                kwargs[f] = getattr(self, f)
        if self.spendingType is not None and issubclass(model, SpendingExpense):
            kwargs["spendingType"] = self.spendingType
        kwargs.update(self.extra)
        return model(**kwargs)
